name: Trigger auto deployment for tvisaabackendv2

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TVISAABACKENDV2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TVISAABACKENDV2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TVISAABACKENDV2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and Deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}

          registryUrl: tvisaacontainers-dnhfhybsbjb3cwef.azurecr.io
          registryUsername: ${{ secrets.TVISAABACKENDV2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TVISAABACKENDV2_REGISTRY_PASSWORD }}

          containerAppName: tvisaabackendv2
          resourceGroup: Tvisaa_for_you

          imageToBuild: tvisaacontainers-dnhfhybsbjb3cwef.azurecr.io/tvisaa-backend:${{ github.sha }}
